all:
  children:
    vps_publica:
      hosts:
        digitalocean:
          ansible_host: 64.227.108.23
          ansible_user: root

    servidores_casa:
      vars:
        ansible_user: deploy
      hosts:
        app1:
          ansible_host: 192.168.100.224
        runner:
          ansible_user: runner
          ansible_host: 192.168.100.225
